spring:
  application: passhelper
  passhelper:
    datasource:
      druid:
        url: jdbc:mysql://localhost:3306/passhelper?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        initial-size: 1
        max-active: 100
        min-idle: 1
        test-while-idle: true
        validation-query: select 1
        filter:
          stat:
            enabled: false

server:
  port: 9999

#mybatis:
  #type-aliases-package: com.example.domain.model
  #type-handlers-package: com.example.typehandler
  #configuration:
    #map-underscore-to-camel-case: true
    #default-fetch-size: 100
    #default-statement-timeout: 30
debug: true